#!/usr/bin/env python3
"""Run clang-tidy using the compile database generated by Meson."""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
from pathlib import Path

EXTENSIONS = (".cpp", ".cc", ".cxx")
SKIP_DIRS = {"subprojects", ".agents"}


def collect(root: Path) -> list[Path]:
    collected_files: list[Path] = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        if any(
            part in SKIP_DIRS or part.startswith(".") or part.startswith("build")
            for part in path.relative_to(root).parts[:-1]
        ):
            continue
        if path.suffix in EXTENSIONS:
            collected_files.append(path)
    return collected_files


def collect_from_compile_commands(source_root: Path, build_root: Path) -> list[Path]:
    compile_db = build_root / "compile_commands.json"
    if not compile_db.exists():
        return collect(source_root)

    entries = json.loads(compile_db.read_text())
    collected_files: list[Path] = []
    seen: set[Path] = set()
    for entry in entries:
        path = Path(entry["file"]).resolve()
        try:
            relative_parent_parts = path.relative_to(source_root).parts[:-1]
        except ValueError:
            continue
        if any(
            part in SKIP_DIRS or part.startswith(".") or part.startswith("build")
            for part in relative_parent_parts
        ):
            continue
        if path.suffix not in EXTENSIONS or path in seen:
            continue
        seen.add(path)
        collected_files.append(path)
    return collected_files


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-root", required=True, type=Path)
    parser.add_argument("--build-root", required=True, type=Path)
    parsed_arguments = parser.parse_args()

    source_root = parsed_arguments.source_root.resolve()
    build_root = parsed_arguments.build_root.resolve()
    source_files = collect_from_compile_commands(source_root, build_root)
    if not source_files:
        return 0

    clang_tidy_path = shutil.which("clang-tidy")
    if clang_tidy_path is None:
        for candidate in (
            Path("/opt/homebrew/opt/llvm/bin/clang-tidy"),
            Path("/usr/local/opt/llvm/bin/clang-tidy"),
        ):
            if candidate.exists():
                clang_tidy_path = str(candidate)
                break

    if clang_tidy_path is None:
        print("clang-tidy not found on PATH; skipping", file=sys.stderr)
        return 0

    command = [clang_tidy_path, f"-p={build_root}"]
    if sys.platform == "darwin":
        sdk_result = subprocess.run(
            ["xcrun", "--show-sdk-path"],
            check=False,
            capture_output=True,
            text=True,
        )
        if sdk_result.returncode == 0:
            command += ["--extra-arg=-isysroot", f"--extra-arg={sdk_result.stdout.strip()}"]

    command += [str(source_file) for source_file in source_files]
    return subprocess.call(command)


if __name__ == "__main__":
    sys.exit(main())
